services:
  - type: web
    name: digipay-eu
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT src.main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PCI_DSS_MODE
        value: strict
      - key: GDPR_RETENTION_DAYS
        value: 2555
      - key: PSD2_SCA_ENABLED
        value: true

